// SHINI v4 clean-room single runtime. No compressed payloads, eval, or legacy route dependencies.

// ---- config.js ----
const BUILD='4.0.0';
const PRODUCT='SHINI';
const FULL_NAME='Surplus, Holdings, Indebtedness, Net Worth & Impairment';
const CLOUD={url:'https://nujmuknvhgyoxhxuvscx.supabase.co',key:'sb_publishable_Ru93CuLz7aHzasR8KRuOvg_tth070WZ',authFunction:'shini-auth'};
const STORAGE={session:'shini_cloud_session_v4',login:'shini_cloud_login_v4',rev:'shini_cloud_revision_v4',ui:'shini_ui_v4',cacheDb:'shini-v4-cache'};
const NAV=[['dashboard','Overview'],['transactions','Transactions'],['budget','Budget & Planner'],['recurring','Recurring'],['accounts','Accounts'],['debt','Debt & Credit'],['goals','Goals'],['networth','Net Worth'],['investments','Investments'],['protection','Protection'],['analytics','Analytics'],['daybook','Cash Day Book'],['bulk','Bulk Import'],['definitions','Definitions'],['tools','Tools & Resources'],['data','Data & Sync'],['settings','Settings'],['diagnostics','Diagnostics']];
const PERIODS=[['current_month','Current month'],['previous_month','Previous month'],['last_3','Last 3 months'],['last_6','Last 6 months'],['current_quarter','Current FY quarter'],['q1','FY Q1 · Apr–Jun'],['q2','FY Q2 · Jul–Sep'],['q3','FY Q3 · Oct–Dec'],['q4','FY Q4 · Jan–Mar'],['current_fy','Current financial year'],['previous_fy','Previous financial year'],['current_year','Current calendar year'],['previous_year','Previous calendar year'],['all','All recorded history'],['custom','Custom date range']];

// ---- crypto.js ----
const enc=new TextEncoder(),dec=new TextDecoder();
const b64={enc:x=>{const a=x instanceof ArrayBuffer?new Uint8Array(x):x;let s='';for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)},dec:s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
async function derive(password,saltB64){const salt=b64.dec(saltB64);const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,256);const verifier=b64.enc(await crypto.subtle.digest('SHA-256',bits));const key=await crypto.subtle.importKey('raw',bits,{name:'AES-GCM'},false,['encrypt','decrypt']);return{key,verifier}}
async function encryptState(obj,key){const iv=crypto.getRandomValues(new Uint8Array(12));const plain=enc.encode(JSON.stringify(obj));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return{v:1,iv:b64.enc(iv),data:b64.enc(cipher),savedAt:new Date().toISOString()}}
async function decryptState(bundle,key){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64.dec(bundle.iv)},key,b64.dec(bundle.data));return JSON.parse(dec.decode(plain))}

// ---- model.js ----
const nowISO=()=>new Date().toISOString();
const id=(p='id')=>`${p}_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=()=>dateKey(new Date());
const defaultCatalogs=()=>({transactionTypes:[['txt_expense','Expense / consumption','expense'],['txt_income','Income','income'],['txt_borrowing','Borrowing / loan inflow','borrowing'],['txt_repayment','Debt / EMI repayment','repayment'],['txt_investment','Investment / asset transfer','investment'],['txt_transfer','Own-account transfer','transfer']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true})),incomeSources:[['inc_salary','Salary / wages','salary'],['inc_business','Business / freelance','business_freelance'],['inc_rental','Rental income','rental'],['inc_investment','Investment income / interest / dividend','investment_income'],['inc_pension','Pension / retirement income','pension'],['inc_gift_refund','Gift / refund / reimbursement','gift_refund'],['inc_other','Other income','other_income']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true})),scopes:[['scope_self','Self','self'],['scope_family','Family','family'],['scope_business','Business','business'],['scope_reimbursable','Reimbursable','reimbursable']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true})),natures:[['nat_spontaneous','Spontaneous','spontaneous'],['nat_recurring','Recurring','recurring'],['nat_one_time','One-time','one_time'],['nat_investment','Investment','investment'],['nat_repayment','Repayment','repayment'],['nat_refund','Refund / reimbursement','refund'],['nat_imported','Imported','imported'],['nat_other','Other','other']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true})),paymentMethods:[['pm_upi','UPI','upi'],['pm_card','Card','card'],['pm_bank_transfer','Bank transfer','bank_transfer'],['pm_cash','Cash','cash'],['pm_auto_debit','Auto debit','auto_debit'],['pm_bnpl','BNPL','bnpl'],['pm_emi','EMI','emi'],['pm_wallet','Wallet','wallet'],['pm_bank','Bank','bank'],['pm_other','Other','other']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true})),units:[['unit_litre','Litres','litre','L'],['unit_km','Kilometres','distance','km'],['unit_meal','Meals','meal','meal'],['unit_order','Orders','order','order'],['unit_item','Items','item','item'],['unit_electricity','Electricity units','electricity','unit'],['unit_gb','GB','data','GB'],['unit_use','Uses','use','use'],['unit_trip','Trips','trip','trip']].map(([id,label,semantic,symbol])=>({id,label,semantic,symbol,active:true,system:true})),accountTypes:[['atype_bank','Bank','bank'],['atype_cash','Cash','cash'],['atype_wallet','Wallet','wallet'],['atype_credit','Credit card','credit'],['atype_bnpl','BNPL','bnpl'],['atype_borrowed','Borrowed funds','borrowed'],['atype_investment','Investment account','investment']].map(([id,label,semantic])=>({id,label,semantic,active:true,system:true}))});
function freshState(username='Personal'){return{version:'4.0.0',createdAt:nowISO(),updatedAt:nowISO(),settings:{profileName:`${username} — Personal`,currency:'INR',monthlyIncome:79160,expenseCap:69000,optimizationTarget:62100,incomeDay:30,emergencyMonths:6,lowBalanceFloor:10000,shiniUI:{}},catalogs:defaultCatalogs(),categories:[{id:'other',name:'Other',group:'Other',budget:0,essential:false,character:'variable',budgetClass:'want',active:true}],accounts:[{id:'acc_primary',name:'Primary Bank Account',type:'bank',accountTypeId:'atype_bank',balance:0,includeLiquidity:true,scope:'self',active:true},{id:'acc_cash',name:'Cash in Hand',type:'cash',accountTypeId:'atype_cash',balance:0,includeLiquidity:true,scope:'self',active:true},{id:'acc_other',name:'Other / Secondary Account',type:'bank',accountTypeId:'atype_bank',balance:0,includeLiquidity:true,scope:'self',active:true}],transactions:[],recurring:[],debts:[],goals:[],assets:[],investments:[],insurance:[],revisions:[],audit:[],snapshots:[],decisions:[],checkins:[],creditProfile:{history:[]},meta:{}}}
function normalizeState(s){s=s&&typeof s==='object'?s:freshState();s.settings={...freshState().settings,...(s.settings||{})};s.catalogs=s.catalogs||defaultCatalogs();for(const[k,v]of Object.entries(defaultCatalogs())){if(!Array.isArray(s.catalogs[k]))s.catalogs[k]=v;else for(const d of v)if(!s.catalogs[k].some(x=>x.id===d.id))s.catalogs[k].push(d)}for(const k of ['categories','accounts','transactions','recurring','debts','goals','assets','investments','insurance','revisions','audit','snapshots','decisions','checkins'])if(!Array.isArray(s[k]))s[k]=[];s.meta=s.meta||{};s.version=s.version||'legacy';return s}
function catalogItem(s,key,id){return s.catalogs?.[key]?.find(x=>x.id===id)}
function semantic(s,t){return catalogItem(s,'transactionTypes',t.transactionTypeId)?.semantic||t.type||'expense'}
function activeTx(s){return s.transactions.filter(t=>!t.archived)}
function money(s,v){const n=Number(v||0);return new Intl.NumberFormat('en-IN',{style:'currency',currency:s.settings?.currency||'INR',minimumFractionDigits:Math.abs(n-Math.round(n))>.004?2:0,maximumFractionDigits:2}).format(n)}
function accountEffect(s,t,sign=1){if(t.archived||t.balanceImpactApplied===false||t.nature==='imported')return;const src=s.accounts.find(a=>a.id===t.accountId),dst=s.accounts.find(a=>a.id===t.toAccountId),amt=Number(t.amount||0)*sign,type=semantic(s,t);if(['transfer','investment'].includes(type)){if(src)src.balance=Number(src.balance||0)-amt;if(dst)dst.balance=Number(dst.balance||0)+amt}else if(type==='repayment'){if(src)src.balance=Number(src.balance||0)-amt;if(dst)dst.balance=Number(dst.balance||0)+amt}else if(type==='expense'){if(src)src.balance=Number(src.balance||0)-amt}else if(['income','borrowing'].includes(type)){if(src)src.balance=Number(src.balance||0)+amt}}
function debtEffect(s,t,sign=1){if(t.archived||t.debtImpactApplied===false||t.nature==='imported'||!t.debtId)return;const d=s.debts.find(x=>x.id===t.debtId);if(!d)return;const type=semantic(s,t);if(type==='borrowing')d.outstanding=Math.max(0,Number(d.outstanding||0)+Number(t.amount||0)*sign);if(type==='repayment')d.outstanding=Math.max(0,Number(d.outstanding||0)-Number(t.principalComponent||0)*sign)}
function periodRange(preset,from='',to=''){const n=new Date(),y=n.getFullYear(),m=n.getMonth();let a,b;const endMonth=(yy,mm)=>new Date(yy,mm+1,0,23,59,59,999);const fyStartYear=m>=3?y:y-1;switch(preset){case'previous_month':a=new Date(y,m-1,1);b=endMonth(y,m-1);break;case'last_3':a=new Date(y,m-2,1);b=endMonth(y,m);break;case'last_6':a=new Date(y,m-5,1);b=endMonth(y,m);break;case'current_fy':a=new Date(fyStartYear,3,1);b=new Date(fyStartYear+1,2,31,23,59,59,999);break;case'previous_fy':a=new Date(fyStartYear-1,3,1);b=new Date(fyStartYear,2,31,23,59,59,999);break;case'q1':a=new Date(fyStartYear,3,1);b=endMonth(fyStartYear,5);break;case'q2':a=new Date(fyStartYear,6,1);b=endMonth(fyStartYear,8);break;case'q3':a=new Date(fyStartYear,9,1);b=endMonth(fyStartYear,11);break;case'q4':a=new Date(fyStartYear+1,0,1);b=endMonth(fyStartYear+1,2);break;case'current_quarter':{const q=m>=3&&m<=5?'q1':m<=8&&m>=6?'q2':m>=9?'q3':'q4';return periodRange(q)}case'current_year':a=new Date(y,0,1);b=new Date(y,11,31,23,59,59,999);break;case'previous_year':a=new Date(y-1,0,1);b=new Date(y-1,11,31,23,59,59,999);break;case'all':return{from:null,to:null};case'custom':a=from?new Date(from+'T00:00:00'):new Date(y,m,1);b=to?new Date(to+'T23:59:59.999'):endMonth(y,m);break;default:a=new Date(y,m,1);b=endMonth(y,m)}return{from:a,to:b}}
function filterPeriod(s,range){return activeTx(s).filter(t=>{if(!range.from)return true;const d=new Date(`${t.date}T${t.time||'12:00'}`);return d>=range.from&&d<=range.to})}
function metrics(s,tx){let income=0,expense=0,repayment=0,borrowing=0,investment=0,transfer=0;for(const t of tx){const a=Number(t.amount||0),type=semantic(s,t);if(type==='income')income+=a;else if(type==='expense')expense+=a;else if(type==='repayment')repayment+=a;else if(type==='borrowing')borrowing+=a;else if(type==='investment')investment+=a;else if(type==='transfer')transfer+=a}const liquid=s.accounts.filter(a=>a.active!==false&&a.includeLiquidity!==false).reduce((z,a)=>z+Number(a.balance||0),0);const debt=s.debts.filter(d=>d.active!==false).reduce((z,d)=>z+Number(d.outstanding||0),0);const assets=s.assets.reduce((z,a)=>z+Number(a.currentValue??a.value??0),0)+s.investments.reduce((z,i)=>z+Number(i.currentValue??i.value??0),0);return{income,expense,repayment,borrowing,investment,transfer,outgo:expense+repayment,net:income+borrowing-expense-repayment-investment,liquid,debt,assets,networth:liquid+assets-debt}}

// ---- tools.js ----
const fv=(monthly,ratePct,months,step=0)=>{let v=0,p=monthly;for(let m=1;m<=months;m++){v=(v+p)*(1+ratePct/1200);if(step&&m%12===0)p*=1+step/100}return v};
const emi=(principal,annualRate,months)=>{const r=annualRate/1200;if(!r)return principal/months;return principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1)};
const fd=(principal,annualRate,years,comp=4)=>principal*Math.pow(1+annualRate/100/comp,comp*years);
const futureCost=(today,inflation,years)=>today*Math.pow(1+inflation/100,years);
const gst=(amount,rate,inclusive=false)=>inclusive?{base:amount/(1+rate/100),gst:amount-amount/(1+rate/100)}:{base:amount,gst:amount*rate/100,total:amount*(1+rate/100)};
function xirr(flows,guess=.1){if(!flows.length)return NaN;const t0=new Date(flows[0].date);let r=guess;for(let k=0;k<60;k++){let f=0,df=0;for(const x of flows){const y=(new Date(x.date)-t0)/(365*864e5),p=Math.pow(1+r,y);f+=x.amount/p;df-=y*x.amount/(p*(1+r))}const nr=r-f/df;if(!Number.isFinite(nr))break;if(Math.abs(nr-r)<1e-8)return nr;r=nr}return r}

// ---- import-export.js ----
const CSV_FIELDS=['record_id','date','time','transaction_type_id','income_source_id','category_id','account_id','destination_account_id','scope_id','nature_id','payment_method_id','merchant','amount','quantity','unit_id','km','value','debt_id','principal_component','interest_component','reimbursable','note','import_action'];
function parseCSV(text){const rows=[];let row=[],v='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);v='';if(row.some(x=>x!==''))rows.push(row);row=[]}else v+=c}if(v||row.length){row.push(v);rows.push(row)}if(!rows.length)return[];const h=rows.shift().map(x=>x.trim().replace(/^\ufeff/,''));return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function canonicalToTx(s,r){const txType=s.catalogs.transactionTypes.find(x=>x.id===r.transaction_type_id);if(!txType)throw new Error(`Unknown transaction type ${r.transaction_type_id}`);if(!s.accounts.some(a=>a.id===r.account_id))throw new Error(`Unknown account ${r.account_id}`);if(r.destination_account_id&&!s.accounts.some(a=>a.id===r.destination_account_id))throw new Error(`Unknown destination ${r.destination_account_id}`);if(r.category_id&&!s.categories.some(c=>c.id===r.category_id))throw new Error(`Unknown category ${r.category_id}`);const amount=Number(r.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('Invalid amount');return{id:r.record_id||id('tx'),externalId:r.record_id||'',date:r.date,time:r.time||'',transactionTypeId:r.transaction_type_id,type:txType.semantic,incomeSourceId:r.income_source_id||'',categoryId:r.category_id||'other',accountId:r.account_id,toAccountId:r.destination_account_id||'',scopeId:r.scope_id||'scope_self',scope:s.catalogs.scopes.find(x=>x.id===(r.scope_id||'scope_self'))?.semantic||'self',natureId:r.nature_id||'nat_imported',nature:s.catalogs.natures.find(x=>x.id===(r.nature_id||'nat_imported'))?.semantic||'imported',paymentMethodId:r.payment_method_id||'pm_other',merchant:r.merchant||'',amount,quantity:Number(r.quantity||0),unitId:r.unit_id||'',km:Number(r.km||0),value:Number(r.value||0),debtId:r.debt_id||'',principalComponent:Number(r.principal_component||0),interestComponent:Number(r.interest_component||0),reimbursable:/^(1|true|yes)$/i.test(r.reimbursable||''),note:r.note||'',createdAt:nowISO(),updatedAt:nowISO(),archived:false,balanceImpactApplied:true,debtImpactApplied:true,fingerprint:`exchange:${r.record_id||''}`}}
function stageCanonical(s,rows){const active=activeTx(s);return rows.map((r,i)=>{try{const tx=canonicalToTx(s,r);const exact=active.find(x=>x.externalId&&x.externalId===tx.externalId)||active.find(x=>x.fingerprint&&x.fingerprint===tx.fingerprint);const possible=active.find(x=>x.date===tx.date&&Number(x.amount)===tx.amount&&x.accountId===tx.accountId&&String(x.merchant||'').toLowerCase()===String(tx.merchant||'').toLowerCase());return{index:i+1,row:r,tx,status:exact?'exact':possible?'possible':'new',match:exact||possible||null,action:(r.import_action||'').toUpperCase()||(exact?'SKIP':'ADD')}}catch(e){return{index:i+1,row:r,error:e.message,status:'invalid',action:'SKIP'}}})}
function commitStage(s,stage){const before=[];let added=0,replaced=0;for(const item of stage){if(item.error||item.action==='SKIP')continue;if(item.action==='REPLACE'&&item.match){before.push(structuredClone(item.match));accountEffect(s,item.match,-1);debtEffect(s,item.match,-1);Object.assign(item.match,item.tx,{id:item.match.id,createdAt:item.match.createdAt,updatedAt:nowISO()});accountEffect(s,item.match,1);debtEffect(s,item.match,1);replaced++}else{const tx={...item.tx,id:item.action==='KEEP_BOTH'?id('tx'):item.tx.id};s.transactions.push(tx);accountEffect(s,tx,1);debtEffect(s,tx,1);added++}}const batch={id:id('import'),at:nowISO(),entityType:'import_batch',action:'bulk_import',summary:`Added ${added}, replaced ${replaced}`,before,after:{added,replaced}};s.revisions.unshift(batch);s.meta.lastImportAt=nowISO();return{added,replaced,batch}}
function csvEscape(v){const s=String(v??'');return/[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function txToCanonical(t){return[t.externalId||t.id,t.date,t.time||'',t.transactionTypeId||'',t.incomeSourceId||'',t.categoryId||'',t.accountId||'',t.toAccountId||'',t.scopeId||'',t.natureId||'',t.paymentMethodId||'',t.merchant||'',t.amount,t.quantity||'',t.unitId||'',t.km||'',t.value||'',t.debtId||'',t.principalComponent||'',t.interestComponent||'',t.reimbursable?'true':'false',t.note||'','ADD']}
function exportCSV(s,tx){return [CSV_FIELDS.join(','),...tx.map(t=>txToCanonical(t).map(csvEscape).join(','))].join('\r\n')}
function download(name,content,type='text/plain'){const b=content instanceof Blob?content:new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
