import fs from 'node:fs';
import vm from 'node:vm';
const root='app/shini/';
const read=p=>fs.readFileSync(root+p,'utf8');
const exists=p=>fs.existsSync(root+p);
const pass=[],fail=[];const check=(n,v)=>{(v?pass:fail).push(n)};
const index=read('index.html'),core=read('app-core.js'),cloud=read('ui-cloud.js'),ui=read('app-ui.js'),css=read('styles.css'),sw=read('sw.js');
for(const f of ['index.html','app-core.js','ui-cloud.js','app-ui.js','styles.css','sw.js','assets/shini-logo.png'])check(`exists ${f}`,exists(f));
check('No legacy hidden runtime',!fs.existsSync('hiden'));
check('No compressed runtime directory',!exists('runtime'));
check('No DecompressionStream',!/(DecompressionStream)/.test(index+core+cloud+ui));
check('No eval',!/(\beval\s*\(|new Function\s*\()/.test(index+core+cloud+ui));
check('No legacy route reference',!/(\/hiden\/vasu|hiden\/vasu)/i.test(index+core+cloud+ui+css+sw));
check('No visible legacy product name',!/(Value\s*&?\s*Asset Stewardship Utility|Central VASU account|Your VASU password|Sign in & open VASU)/i.test(index+core+cloud+ui));
check('Canonical SHINI title',/Surplus, Holdings, Indebtedness, Net Worth &amp; Impairment/.test(index));
check('Login SHINI placeholders',/Your SHINI username/.test(index)&&/Your SHINI password/.test(index));
check('Master logo used',/assets\/shini-logo\.png/.test(index));
check('New SHINI auth endpoint',/authFunction:'shini-auth'/.test(core));
check('PBKDF2 250k SHA-256',/iterations:250000/.test(core)&&/SHA-256/.test(core));
check('AES-GCM encrypted vault',/AES-GCM/.test(core)&&/encryptState/.test(core)&&/decryptState/.test(core));
check('Central finance_vault',/finance_vault/.test(cloud));
check('Optimistic cloud revision',/revision=eq/.test(cloud));
check('Cloud conflict guard',/Cloud revision conflict/.test(cloud));
check('No service role secret',!/service[_-]?role/i.test(index+core+cloud+ui));
check('Global period presets',/previous_fy/.test(core)&&/last_6/.test(core)&&/custom/.test(core));
check('Indian FY Apr start',/fyStartYear/.test(core));
check('Accounting semantics',/borrowing/.test(core)&&/repayment/.test(core)&&/investment/.test(core)&&/transfer/.test(core));
check('Account effect',/function accountEffect/.test(core));
check('Debt effect',/function debtEffect/.test(core));
check('Stable master catalogs',/transactionTypes/.test(core)&&/incomeSources/.test(core)&&/paymentMethods/.test(core)&&/units/.test(core));
check('Bulk import staging',/Bulk Import/.test(ui)&&/commitImport/.test(ui));
check('Duplicate merge actions',/KEEP_BOTH/.test(core+ui)&&/REPLACE/.test(core+ui)&&/SKIP/.test(core+ui));
check('CSV JSON XLSX contract mentioned',/CSV_FIELDS/.test(core));
check('Export capabilities',/CSV/.test(ui)&&/JSON/.test(ui)&&/Print/.test(ui));
check('Cash Day Book',/Cash Day Book/.test(core+ui));
check('Tools hub',/Tools & Resources/.test(core+ui));
check('Three text color controls',/primary/.test(ui)&&/secondary/.test(ui)&&/accent/.test(ui));
check('Mobile dock',/mobileDock/.test(index+ui));
check('Touch-scroll sidebar',/overflow-y:\s*auto/.test(css)&&/-webkit-overflow-scrolling:\s*touch/.test(css));
check('Service worker scoped to SHINI',/\/app\/shini\//.test(sw));
check('Service worker does not intercept cross origin',/u\.origin!==self\.location\.origin|url\.origin !== self\.location\.origin/.test(sw));
check('Diagnostics page',/Diagnostics/.test(core+ui));
check('No runtime dependency on VASU brand mapper',!/SHINI_REFRESH_BRAND|shini-brand-safe/.test(index+core+cloud+ui));
for(const [name,src] of [['core',core],['cloud',cloud],['ui',ui],['sw',sw]]){try{new vm.Script(src);check(`syntax ${name}`,true)}catch(e){console.error(name,e.message);check(`syntax ${name}`,false)}}
const png=fs.readFileSync(root+'assets/shini-logo.png');check('Logo PNG signature',png.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])));check('Logo nontrivial',png.length>5000);
console.log(`SHINI v4 QA: ${pass.length} PASS / ${fail.length} FAIL`);for(const x of pass)console.log('PASS',x);for(const x of fail)console.error('FAIL',x);if(fail.length)process.exit(1);
