import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const parts=['app-v42-core.js','app-v42-ledger.js','app-v42-crud.js','app-v42-imports.js','app-v42-platform.js'];
const src=parts.map(p=>fs.readFileSync(new URL('./'+p,import.meta.url),'utf8')).join('\n');
const pass=[],fail=[];const ok=(n,v)=>{(v?pass:fail).push(n)};
for(const token of ['deleteAuth','PBKDF2','tombstones','hardDeleteDefinition','remapDefinition','mergeImported','stageMasterImport','notificationState','Documents & Renewals','data-v42-delete-tx','recordPayment','manualFields','Merge and delete account'])ok(`contains ${token}`,src.includes(token));
const ctx={console,crypto:webcrypto,TextEncoder,TextDecoder,Intl,Date,Map,Set,Math,Number,String,Boolean,Array,Object,RegExp,Error,Promise,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);
const A=ctx.SHINIV42;ok('API exported',!!A&&A.VERSION==='4.2.0');
const s={settings:{currency:'INR',lowBalanceFloor:1000},catalogs:{transactionTypes:[{id:'txt_expense',label:'Expense',semantic:'expense',active:true,system:true},{id:'txt_income',label:'Income',semantic:'income',active:true,system:true}],incomeSources:[{id:'inc_other',label:'Other',semantic:'other',active:true,system:true}],paymentMethods:[{id:'pm_other',label:'Other',semantic:'other',active:true,system:true}],scopes:[{id:'scope_self',label:'Self',semantic:'self',active:true,system:true}],natures:[{id:'nat_other',label:'Other',semantic:'other',active:true,system:true}],units:[{id:'unit_item',label:'Item',semantic:'item',active:true,system:true}],accountTypes:[{id:'atype_bank',label:'Bank',semantic:'bank',active:true,system:true}]},categories:[{id:'other',name:'Other',active:true,system:true},{id:'food',name:'Food',active:true,system:false}],accounts:[{id:'a1',name:'A1',accountTypeId:'atype_bank',balance:1000,active:true},{id:'a2',name:'A2',accountTypeId:'atype_bank',balance:50,active:true}],transactions:[{id:'t1',externalId:'e1',date:'2026-08-01',transactionTypeId:'txt_expense',categoryId:'food',accountId:'a1',scopeId:'scope_self',natureId:'nat_other',paymentMethodId:'pm_other',amount:10,merchant:'Cafe',manualFields:[]}],recurring:[{id:'r1',name:'Cafe',amount:10,categoryId:'food',accountId:'a1',paymentMethodId:'pm_other',active:true,manualFields:[]}],debts:[],goals:[],assets:[],investments:[],insurance:[],meta:{}};
A.ensure(s);ok('state migration',Array.isArray(s.documents)&&!!s.meta.v42?.tombstones?.transactions);
ok('definition refs',A.definitionRefs(s,'categories','food').length===2);
A.createDefinition(s,'categories',{id:'meals',label:'Meals'});ok('definition create',s.categories.some(x=>x.id==='meals'));
let semanticBlocked=false; try{A.createDefinition(s,'transactionTypes',{id:'txt_bad',label:'Bad',semantic:'mystery'})}catch{semanticBlocked=true} ok('invalid accounting semantic blocked',semanticBlocked);
await A.hardDeleteDefinition(s,'categories','food','meals');ok('definition remap+delete',!s.categories.some(x=>x.id==='food')&&s.transactions[0].categoryId==='meals'&&s.recurring[0].categoryId==='meals');
const ex={id:'g1',name:'Manual name',target:100,manualFields:['name']},inc={id:'g1',name:'Imported name',target:200};const merged=A.mergeImported(ex,inc);ok('manual field preserved',merged.name==='Manual name'&&merged.target===200);
ok('account refs',A.accountRefs(s,'a1').length>=2);A.remapAccount(s,'a1','a2');ok('account remap',s.transactions[0].accountId==='a2'&&s.recurring[0].accountId==='a2');
let st=A.stageMasterImport(s,'goals',[{goal_id:'g2',name:'Emergency',target_amount:'5000',account_id:'a2',active:'true'},{goal_id:'g2',name:'Duplicate',target_amount:'1'}]);ok('duplicate import rejected',st[1].errors.some(x=>x.includes('duplicate stable ID')));
st=A.stageMasterImport(s,'goals',[{goal_id:'g3',name:'Goal 3',target_amount:'3000',account_id:'a2',active:'true'}]);const cr=A.commitMasterImport(s,'goals',st);ok('master import commit',cr.added===1&&s.goals.some(x=>x.id==='g3'));
s.documents.push({id:'doc1',name:'Licence',expiryDate:'2026-08-18',active:true,manualFields:[]});ok('document notification',A.notifyRecords(s).some(x=>x.kind==='document'));
s.meta.v42.tombstones.transactions.e9={at:new Date().toISOString()};ok('tombstone match',A.isTombstoned(s,{record_id:'e9'}));
s.recurring.push({id:'due1',name:'Subscription',amount:25,nextDate:'2026-08-17',categoryId:'meals',accountId:'a2',active:true,manualFields:[]});
ok('active notification derived',A.activeNotifications(s).some(x=>x.kind==='recurring'));
const audit=A.auditV42(s);ok('audit result shape',Array.isArray(audit.fail)&&Array.isArray(audit.warn)&&Array.isArray(audit.pass));
console.log(`SHINI v4.2 QA: ${pass.length} PASS / ${fail.length} FAIL`);for(const x of pass)console.log('PASS',x);for(const x of fail)console.error('FAIL',x);if(fail.length)process.exit(1);
