import fs from 'node:fs';
import vm from 'node:vm';
const root='app/shini/';
const read=p=>fs.readFileSync(root+p,'utf8');
const check=(name,ok)=>{if(!ok)throw new Error(name)};
globalThis.metrics=(s,tx)=>{let income=0,expense=0,repayment=0,borrowing=0,investment=0,transfer=0;for(const t of tx){const a=Number(t.amount||0),k=t.type||'expense';if(k==='income')income+=a;else if(k==='expense')expense+=a;else if(k==='repayment')repayment+=a;else if(k==='borrowing')borrowing+=a;else if(k==='investment')investment+=a;else if(k==='transfer')transfer+=a}const liquid=(s.accounts||[]).reduce((z,a)=>z+Number(a.balance||0),0),debt=(s.debts||[]).reduce((z,d)=>z+Number(d.outstanding||0),0);return{income,expense,repayment,borrowing,investment,transfer,net:income+borrowing-expense-repayment-investment,liquid,debt,assets:0,networth:liquid-debt}};
vm.runInThisContext(read('app-v41.js'),{filename:'app-v41.js'});
const A=globalThis.SHINIV41;check('SHINIV41 API export',!!A&&A.VERSION==='4.1.0');
check('Monthly cadence inference',A.inferCadence(['2026-04-05','2026-05-05','2026-06-05'])==='monthly');
check('Annual cadence inference',A.inferCadence(['2025-08-05','2026-08-05'])==='annual');
check('Month-end clamp',A.addCadence('2026-01-31','monthly')==='2026-02-28');
const s={settings:{currency:'INR',lowBalanceFloor:1000},catalogs:{transactionTypes:[{id:'txt_expense',semantic:'expense'},{id:'txt_income',semantic:'income'},{id:'txt_borrowing',semantic:'borrowing'},{id:'txt_repayment',semantic:'repayment'},{id:'txt_transfer',semantic:'transfer'}],scopes:[{id:'scope_self'}],paymentMethods:[{id:'pm_upi'},{id:'pm_auto_debit'}],units:[]},categories:[{id:'food',name:'Food'},{id:'emi',name:'EMI'},{id:'other',name:'Other'}],accounts:[{id:'acc_primary',name:'Bank',balance:5000,includeLiquidity:true,active:true},{id:'acc_other',name:'Wallet',balance:2000,includeLiquidity:true,active:true}],transactions:[{id:'e1',externalId:'e1',date:'2026-04-05',transactionTypeId:'txt_expense',type:'expense',categoryId:'food',accountId:'acc_primary',scopeId:'scope_self',paymentMethodId:'pm_upi',merchant:'Cafe',amount:100},{id:'e2',externalId:'e2',date:'2026-05-05',transactionTypeId:'txt_expense',type:'expense',categoryId:'food',accountId:'acc_primary',scopeId:'scope_self',paymentMethodId:'pm_upi',merchant:'Cafe',amount:120},{id:'b1',externalId:'b1',date:'2026-06-01',transactionTypeId:'txt_borrowing',type:'borrowing',categoryId:'emi',accountId:'acc_primary',scopeId:'scope_self',paymentMethodId:'pm_upi',merchant:'Example Finance loan disbursal',amount:10000},{id:'r1',externalId:'r1',date:'2026-07-01',transactionTypeId:'txt_repayment',type:'repayment',categoryId:'emi',accountId:'acc_primary',scopeId:'scope_self',paymentMethodId:'pm_auto_debit',merchant:'Example Finance',amount:1000,debtId:'d1',principalComponent:800}],debts:[{id:'d1',provider:'Example Finance',principalAmount:10000,emiAmount:1000,annualInterestRate:12,tenureMonths:12,outstanding:9200,active:true,dueDay:5,autoDebit:true}],recurring:[]};
const cand=A.subscriptionCandidates(s);check('Subscription candidate',cand.some(x=>x.name==='Cafe'&&x.cadence==='monthly'));
const loan=A.loanEstimate(s,s.debts[0]);check('Loan repayment linkage',loan.paidTotal===1000&&loan.paidPrincipal===800);
const audit=A.auditState(s);check('Clean fixture integrity',audit.severe===0);
const broken=structuredClone(s);broken.transactions[0].categoryId='missing_category';check('Orphan category detection',A.auditState(broken).items.some(x=>x.level==='fail'&&x.name==='Unknown category'));
const index=read('index.html'),sw=read('sw.js'),css=read('styles-v41.css');
check('v4.1 script wired',/app-v41\.js\?v=4\.[0-9]+\.0/.test(index));
check('v4.1 stylesheet wired',/styles-v41\.css\?v=4\.[0-9]+\.0/.test(index));
check('v4.1 service-worker cache',/app-v41\.js\?v=4\.[0-9]+\.0/.test(sw)&&/styles-v41\.css\?v=4\.[0-9]+\.0/.test(sw));
check('Transaction filter CSS',/v41-tx-filterbar/.test(css));
check('No legacy visible VASU branding',!/Your VASU|Central VASU|open VASU|Value Asset Stewardship/i.test(index+read('app-v41.js')));
console.log('SHINI v4.1 QA PASS', {version:A.VERSION,subscriptionCandidates:cand.length,loanPaid:loan.paidTotal,auditPasses:audit.pass});
