import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=fs.readFileSync(new URL('./app-v427.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('./sw.js',import.meta.url),'utf8');
const release=JSON.parse(fs.readFileSync(new URL('./release.json',import.meta.url),'utf8'));
for(const marker of ["VERSION='4.2.7'",'Clean rebuild import order','Categories / classification definitions','Account reconciliation anchors','Transactions only · AI-assisted statement workflow','typeof enhanceBulk','data-page="bulk"','v427ImportHost'])assert.ok(js.includes(marker),`missing v4.2.7 marker: ${marker}`);
assert.ok(html.includes('app-v427.js?v='),'v4.2.7 lifecycle layer not wired');
assert.ok(sw.includes('app-v427.js?v='),'v4.2.7 lifecycle asset not cached');
assert.ok(Number(String(release.build).split('.').at(-1))>=7,'release must not regress below v4.2.7');
assert.ok(js.indexOf('typeof enhanceBulk')<js.indexOf('Clean rebuild import order'),'structured enhancer must be invoked before the rebuild guide is decorated');
assert.ok(js.includes('Move the wrapper as a unit'),'structured import wrapper/event host must be preserved');
console.log('SHINI v4.2.7 bulk-import lifecycle invariants PASS');
