// ---- cloud.js ----
let state=null,key=null,revision=0,session=null,passwordCache='';let syncing=false,pending=false,timer=null;
const getState=()=>state;const getRevision=()=>revision;const isUnlocked=()=>!!state&&!!key;const getLogin=()=>localStorage.getItem(STORAGE.login)||'';
const headers=token=>({apikey:CLOUD.key,...(token?{Authorization:`Bearer ${token}`}:{})});
function networkError(label,e){if(e?.name==='AbortError')return new Error(`${label} timed out. Check your connection and try again.`);if(e instanceof TypeError)return new Error(`${label} could not reach the server. Check your connection and try again.`);return e instanceof Error?e:new Error(String(e||`${label} failed`))}
async function fetchTimed(url,opt={},timeoutMs=15000,label='Request'){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(url,{...opt,signal:c.signal})}catch(e){throw networkError(label,e)}finally{clearTimeout(t)}}
function saveSession(x){session=x?{access_token:x.access_token,refresh_token:x.refresh_token,user:x.user,expires_at:x.expires_at||Math.floor(Date.now()/1000)+Number(x.expires_in||3600)}:null;if(session)localStorage.setItem(STORAGE.session,JSON.stringify(session));else localStorage.removeItem(STORAGE.session)}
function loadSession(){if(session)return session;try{session=JSON.parse(localStorage.getItem(STORAGE.session)||'null')}catch{}return session}
async function ensureSession(){let s=loadSession();if(!s)return null;if(Number(s.expires_at||0)>Math.floor(Date.now()/1000)+90)return s;const r=await fetchTimed(`${CLOUD.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})},12000,'Session refresh');const x=await r.json().catch(()=>({}));if(!r.ok){saveSession(null);throw new Error(x.error_description||x.message||'Session expired. Sign in again.')}saveSession(x);return session}
async function auth(login,password,action='login'){const r=await fetchTimed(`${CLOUD.url}/functions/v1/${CLOUD.authFunction}`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({action,login,password})},15000,'Authentication');const x=await r.json().catch(()=>({}));if(!r.ok){if(r.status===503)throw new Error(x.error||'Authentication service is temporarily unavailable. Please try again.');if(r.status===429)throw new Error(x.error||'Too many attempts. Try again later.');throw new Error(x.error||x.message||`Authentication failed (${r.status})`)}saveSession(x);localStorage.setItem(STORAGE.login,login);return x}
async function api(path,opt={},timeoutMs=18000,label='Cloud request'){const s=await ensureSession();if(!s)throw new Error('Sign in again.');return fetchTimed(CLOUD.url+path,{...opt,headers:{...headers(s.access_token),...(opt.headers||{})}},timeoutMs,label)}
async function fetchRow(){const s=await ensureSession();if(!s?.user?.id)throw new Error('Sign in again.');const r=await api(`/rest/v1/finance_vault?select=payload,revision,updated_at&user_id=eq.${encodeURIComponent(s.user.id)}`,{},20000,'Encrypted vault download');const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.message||'Unable to read central vault');if(!Array.isArray(x))throw new Error('Central vault response is invalid.');return x[0]||null}
async function openVault(password){const row=await fetchRow();if(!row)throw new Error('No central SHINI vault exists for this account.');const meta=row.payload?.meta,bundle=row.payload?.bundle;if(!meta?.salt||!meta?.verifier||!bundle?.iv||!bundle?.data)throw new Error('Central vault payload is invalid.');let dk;try{dk=await derive(password,meta.salt)}catch(e){throw new Error('Unable to derive the local vault key on this device.')}if(dk.verifier!==meta.verifier)throw new Error('Password authenticated but does not decrypt this vault.');let decoded;try{decoded=await decryptState(bundle,dk.key)}catch(e){throw new Error('Encrypted vault could not be decrypted. The cloud copy may be damaged or the encryption key does not match.')}state=normalizeState(decoded);key=dk.key;passwordCache=password;revision=Number(row.revision||0);localStorage.setItem(STORAGE.rev,String(revision));await cacheLocal(row.payload);return state}
async function cacheLocal(payload){try{localStorage.setItem('shini_v4_cache',JSON.stringify({payload,revision,savedAt:nowISO()}))}catch{}}
async function save({force=false}={}){if(!state||!key)return false;if(syncing){pending=true;return false}syncing=true;try{state.updatedAt=nowISO();const bundle=await encryptState(state,key),meta=(await fetchRow())?.payload?.meta;if(!meta)throw new Error('Central vault metadata unavailable.');const s=await ensureSession(),next=revision+1,release=globalThis.SHINI_RELEASE_BUILD||BUILD,payload={meta,bundle,appVersion:`SHINI ${release}`,device:navigator.userAgent.slice(0,160)};let r;if(force){r=await api('/rest/v1/finance_vault?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:s.user.id,payload,revision:next,updated_at:nowISO()})},25000,'Encrypted vault synchronization')}else{r=await api(`/rest/v1/finance_vault?user_id=eq.${encodeURIComponent(s.user.id)}&revision=eq.${revision}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({payload,revision:next,updated_at:nowISO()})},25000,'Encrypted vault synchronization')}const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.message||'Central sync failed');if(!force&&(!Array.isArray(x)||!x.length))throw new Error('Cloud revision conflict. Reload the latest central vault before saving.');const row=Array.isArray(x)?x[0]:x;revision=Number(row?.revision||next);localStorage.setItem(STORAGE.rev,String(revision));await cacheLocal(payload);window.dispatchEvent(new CustomEvent('shini:synced',{detail:{revision}}));return true}finally{syncing=false;if(pending){pending=false;clearTimeout(timer);timer=setTimeout(()=>save().catch(console.error),700)}}}
function scheduleSave(){clearTimeout(timer);timer=setTimeout(()=>save().catch(e=>window.dispatchEvent(new CustomEvent('shini:sync-error',{detail:e}))),650)}
async function reload(password=passwordCache){return openVault(password)}
function lock(){state=null;key=null;passwordCache='';session=null;localStorage.removeItem(STORAGE.session)}
