// ---- cloud.js ----
let state=null,key=null,revision=0,session=null,passwordCache='';let syncing=false,pending=false,timer=null;
const getState=()=>state;const getRevision=()=>revision;const isUnlocked=()=>!!state&&!!key;const getLogin=()=>localStorage.getItem(STORAGE.login)||'';
const headers=token=>({apikey:CLOUD.key,...(token?{Authorization:`Bearer ${token}`}:{})});
function saveSession(x){session=x?{access_token:x.access_token,refresh_token:x.refresh_token,user:x.user,expires_at:x.expires_at||Math.floor(Date.now()/1000)+Number(x.expires_in||3600)}:null;if(session)localStorage.setItem(STORAGE.session,JSON.stringify(session));else localStorage.removeItem(STORAGE.session)}
function loadSession(){if(session)return session;try{session=JSON.parse(localStorage.getItem(STORAGE.session)||'null')}catch{}return session}
async function ensureSession(){let s=loadSession();if(!s)return null;if(Number(s.expires_at||0)>Math.floor(Date.now()/1000)+90)return s;const r=await fetch(`${CLOUD.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});const x=await r.json();if(!r.ok)throw new Error(x.error_description||x.message||'Session expired');saveSession(x);return session}
async function auth(login,password,action='login'){const r=await fetch(`${CLOUD.url}/functions/v1/${CLOUD.authFunction}`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({action,login,password})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||x.message||`Authentication failed (${r.status})`);saveSession(x);localStorage.setItem(STORAGE.login,login);return x}
async function api(path,opt={}){const s=await ensureSession();if(!s)throw new Error('Sign in again.');return fetch(CLOUD.url+path,{...opt,headers:{...headers(s.access_token),...(opt.headers||{})}})}
async function fetchRow(){const s=await ensureSession();const r=await api(`/rest/v1/finance_vault?select=payload,revision,updated_at&user_id=eq.${encodeURIComponent(s.user.id)}`);const x=await r.json();if(!r.ok)throw new Error(x.message||'Unable to read central vault');return x[0]||null}
async function openVault(password){const row=await fetchRow();if(!row)throw new Error('No central SHINI vault exists for this account.');const meta=row.payload?.meta,bundle=row.payload?.bundle;if(!meta?.salt||!meta?.verifier||!bundle?.iv||!bundle?.data)throw new Error('Central vault payload is invalid.');const dk=await derive(password,meta.salt);if(dk.verifier!==meta.verifier)throw new Error('Password does not decrypt this vault.');state=normalizeState(await decryptState(bundle,dk.key));key=dk.key;passwordCache=password;revision=Number(row.revision||0);localStorage.setItem(STORAGE.rev,String(revision));await cacheLocal(row.payload);return state}
async function cacheLocal(payload){try{localStorage.setItem('shini_v4_cache',JSON.stringify({payload,revision,savedAt:nowISO()}))}catch{}}
async function save({force=false}={}){if(!state||!key)return false;if(syncing){pending=true;return false}syncing=true;try{state.updatedAt=nowISO();const bundle=await encryptState(state,key),meta=(await fetchRow())?.payload?.meta;if(!meta)throw new Error('Central vault metadata unavailable.');const s=await ensureSession(),next=revision+1,payload={meta,bundle,appVersion:`SHINI ${BUILD}`,device:navigator.userAgent.slice(0,160)};let r;if(force){r=await api('/rest/v1/finance_vault?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:s.user.id,payload,revision:next,updated_at:nowISO()})})}else{r=await api(`/rest/v1/finance_vault?user_id=eq.${encodeURIComponent(s.user.id)}&revision=eq.${revision}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({payload,revision:next,updated_at:nowISO()})})}const x=await r.json();if(!r.ok)throw new Error(x.message||'Central sync failed');if(!force&&(!Array.isArray(x)||!x.length))throw new Error('Cloud revision conflict. Reload the latest central vault before saving.');const row=Array.isArray(x)?x[0]:x;revision=Number(row?.revision||next);localStorage.setItem(STORAGE.rev,String(revision));await cacheLocal(payload);window.dispatchEvent(new CustomEvent('shini:synced',{detail:{revision}}));return true}finally{syncing=false;if(pending){pending=false;clearTimeout(timer);timer=setTimeout(()=>save().catch(console.error),700)}}}
function scheduleSave(){clearTimeout(timer);timer=setTimeout(()=>save().catch(e=>window.dispatchEvent(new CustomEvent('shini:sync-error',{detail:e}))),650)}
async function reload(password=passwordCache){return openVault(password)}
function lock(){state=null;key=null;passwordCache='';session=null;localStorage.removeItem(STORAGE.session)}
